# language: haskell
#
# ghc:
#   - 8.0.2
#
# notifications:
#   email: false

language: generic

sudo: false
cache:
  directories:
    - $HOME/.stack/

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack setup
  - stack build
  - stack install

script:
  - nohup haskyapictl --root . --ip localhost --port 8080 > /dev/null 2>&1 &
  - curl "http://localhost:8080/api/checkout" -i -X POST -d "{ \"order\" : [\"104\"] }"
  - pkill haskyapictl

notifications:
  email: false
