# language: haskell
#
# ghc:
#   - 8.0.2
#
# notifications:
#   email: false

language: generic

sudo: false
cache:
  directories:
    - $HOME/.stack/

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - git clone https://github.com/okue/Haskyapi.git

install:
  - stack setup
  - stack build
  - stack install

script:
  - nohup haskyapictl > /dev/null 2>&1 &
  - pkill haskyapictl

notifications:
  email: false
