name:       haskyapi
version:    0.0.0.1
license:    MIT
author:     "okue"
github:     "okue/haskyapi"
maintainer: "example@example.com"
copyright:  "2017 okue"

extra-source-files:
- README.md

synopsis: HTTP server
category: Web

description: Please see the README on Github at <https://github.com/okue/haskyapi#readme>

dependencies:
- base >= 4.7 && < 5
- split
- containers
- bytestring
- utf8-string
- text
- markdown
- blaze-html
- mtl
- network
- time
- directory
- http-conduit
- split
- tagsoup
- aeson
- persistent
- persistent-template
- persistent-sqlite
- parsec

library:
  source-dirs: src
  other-modules:
  - Web.Haskyapi.Config.Defaults
  - Web.Haskyapi.Config.Parser
  # - Web.Haskyapi.Config.Config

executables:
  haskyapi:
    main: Main.hs
    source-dirs:
    - app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    other-modules:
    - Api.Hapi
    - Model
    - ModelDef
    dependencies:
    - haskyapi

tests:
  test:
    main: Spec.hs
    source-dirs:
    - test
    - app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    other-modules:
    - Api.Hapi
    - Model
    - ModelDef
    dependencies:
    - haskyapi
